### ISSUE TITLE
Transfer repo to `tock` organization?

### ISSUE THREAD

**Issue by alevy** [helena-project/tock-teensy#4]
@shaneleonard 
Since you're off in real-job-land, how do you feel about transferring this repo to the `tock` organization so you're not on the hook for maintaining it anymore? That has the advantage, over forking, that previous links to this repo (of which there are a few) will get redirected to the new one).

**Comment by shaneleonard** [comment]
Will do! Thanks for the suggestion.

**Comment by shaneleonard** [comment]
It looks like I need 'create' access on helena-project before it will let me transfer ownership.

**Comment by phil-levis** [comment]
Awesome -- I was just about to open an issue on this, as I'm writing up the detailed HOWTO for the bike wheel light project.

**Comment by shaneleonard** [comment]
Cool, Phil are you able to give me the create access in Helena Project? I'll be able to transfer ownership tonight if so.

**Comment by shaneleonard** [comment]
Ah, didn't realize there's a separate `tock` organization. I'm assuming that's up to @alevy then?

**Comment by phil-levis** [comment]
I made you an owner in helena-project, you should be able to now. But I think that Amit was thinking the tock organization, which is, for example, where the stm32 port lives.

Phil

sorry shift broken sometimes

**Comment by alevy** [comment]
@shaneleonard just transfer to the helena-project org and I'll handle from there

**Comment by shaneleonard** [comment]
Transferred.
